// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bloom-wallet/api/handler"
	"bloom-wallet/database"
	"bloom-wallet/repository"
	"bloom-wallet/router"
	"bloom-wallet/services"

	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp 由 Wire 生成实现，返回组装好的 *gin.Engine（具体实现在 wire_gen.go）
func InitializeApp() (*gin.Engine, error) {
	testService := services.NewTestService()
	testHandler := handler.NewTestHandler(testService)
	loginService := services.NewLoginService()
	loginHandler := handler.NewLoginHandler(loginService)
	db := database.ProvideDB()
	projectContractRepository := repository.NewProjectContractRepository(db)
	projectContractService := services.NewProjectContractService(projectContractRepository)
	projectContractHandler := handler.NewProjectContractHandler(projectContractService)
	walletService := services.NewWalletService()
	walletHandler := handler.NewWalletHandler(walletService)
	engine := router.SetupRouter(testHandler, loginHandler, projectContractHandler, walletHandler)
	return engine, nil
}
